---
apiVersion: v1
kind: Pod
metadata:
  name: carvel-test-complex-app
spec:
  containers:
    - image: hello-world-carvel-complex
      imagePullPolicy: Always
      name: carvel-test-complex-app

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: hello-world-carvel-complex
    path: .
    ko:
      build:
        rawOptions: ["--disable-optimizations"]
destinations:
  - image: hello-world-carvel-complex
    newImage: ghcr.io/dennisdenuto/hello-world-carvel-complex-app-gh

